apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-management
  namespace: medsync
  labels:
    app: doctor-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-management
  template:
    metadata:
      labels:
        app: doctor-management
    spec:
      containers:
      - name: doctor-management
        image: doctor-management:latest
        ports:
        - containerPort: 3002
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: MONGO_BASE
          valueFrom:
            secretKeyRef:
              name: medsync-secrets
              key: MONGO_BASE
        - name: MONGO_URI
          value: "$(MONGO_BASE)/doctor_db"
        - name: PORT
          value: "3002"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: medsync-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRE
          valueFrom:
            secretKeyRef:
              name: medsync-secrets
              key: JWT_EXPIRE
        - name: FRONTEND_URL
          value: "http://medsync.local"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-management
  namespace: medsync
spec:
  selector:
    app: doctor-management
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP
